name = "line-whoami-bot"
main = "src/index.ts"
compatibility_date = "2025-01-25"

routes = [{ pattern = "line-whoami.dowhy.space", custom_domain = true }]

[vars]
ENABLE_LINE_VERIFY_SIGNATURE = true

[observability]
enabled = true
head_sampling_rate = 1
